### ISSUE TITLE
label mapping cost_tensor broken in numpy 1.24

### ISSUE THREAD

**Issue by CoreyCole** [desh2608/dover-lap#22]
Tested that it is working in `numpy==1.23.5`. Installing `numpy==1.24.0` breaks the label mapping step where the cost_tensor is calculated using `numpy.sum()`

[NEP 34](https://numpy.org/neps/nep-0034-infer-dtype-is-object.html) might be helpful?

```
dover-lap out.rttm egs/ami/rttm_test_* 
```
```
Loading speaker turns from input RTTMs...
Merging overlapping speaker turns...
Processing file EN2002a.Mix-Headset..
Traceback (most recent call last):
  File "/home/corey/anaconda3/envs/omnicom_env/bin/dover-lap", line 33, in <module>
    sys.exit(load_entry_point('dover-lap', 'console_scripts', 'dover-lap')())
  File "/home/corey/anaconda3/envs/omnicom_env/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/corey/anaconda3/envs/omnicom_env/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/media/data/dev/dover-lap/dover_lap/libs/utils.py", line 86, in invoke
    super(CommandOptionRequiredClass, self).invoke(ctx)
  File "/home/corey/anaconda3/envs/omnicom_env/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/corey/anaconda3/envs/omnicom_env/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/media/data/dev/dover-lap/dover_lap/dover_lap.py", line 164, in main
    file_to_out_turns[file_id] = DOVERLap.combine_turns_list(
  File "/media/data/dev/dover-lap/dover_lap/src/doverlap.py", line 26, in combine_turns_list
    mapped_turns_list, weights = LabelMapping.get_mapped_turns_list(
  File "/media/data/dev/dover-lap/dover_lap/src/label_mapping.py", line 31, in get_mapped_turns_list
    label_mapping, weights = greedy_map.compute_mapping(turns_list)
  File "/media/data/dev/dover-lap/dover_lap/src/mapping/greedy.py", line 25, in compute_mapping
    cost_tensor, pairwise_costs = self.compute_cost_tensor(turns_list)
  File "/media/data/dev/dover-lap/dover_lap/src/mapping/greedy.py", line 95, in compute_cost_tensor
    cost_tensor = np.sum(list(pairwise_costs.values()))
  File "<__array_function__ internals>", line 200, in sum
  File "/home/corey/anaconda3/envs/omnicom_env/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 2324, in sum
    return _wrapreduction(a, np.add, 'sum', axis, dtype, out, keepdims=keepdims,
  File "/home/corey/anaconda3/envs/omnicom_env/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.
```

**Comment by desh2608** [comment]
Closing via #21
